# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-09 01:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 11, 9, 3, 16, 26, 364170), verbose_name='Опубликована'),
        ),
    ]
